Updated grpc with clarifai SDK functions
mogith-pn/langchain-fork pull request #1
Opened 2023-11-09 14:03 UTC by mogith-pn

2023-11-09 14:27 UTC, mogith-pn commented
zeiler@clarifai.com 
sai.nivedh@clarifai.com

2023-11-10 08:37 UTC, sainivedh requested changes
Good Work. Added some comments.

2023-11-10 08:37 UTC, sainivedh commented on libs/langchain/langchain/vectorstores/clarifai.py
> -        pat: Optional[str] = None,
We are not removing `pat` as input arg elsewhere(llm, embeddings Clarifai class), any specific reason to remove here?

2023-11-10 08:37 UTC, sainivedh commented on libs/langchain/langchain/vectorstores/clarifai.py
> +                continue
This is not efficient. We are uploading each input once, could be changed to batch operation

2023-11-10 08:37 UTC, sainivedh commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "APP_ID = \"langchain-app-test\"\n",
```suggestion
    "USER_ID = \"USERNAME_ID\"\n",
    "APP_ID = \"APPLICATION_ID\"\n",
```

2023-11-10 08:37 UTC, sainivedh commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "os.environ['CLARIFAI_PAT']='21b7b036432a45c1ade7afd3c271cb4e'"
```suggestion
    "os.environ['CLARIFAI_PAT']= 'CLARIFAI_PAT_TOKEN'"
```

Please make sure to scrub all personal info

2023-11-10 08:37 UTC, sainivedh commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "loader = TextLoader(\"/Users/mogithpn/Downloads/history2.txt\")\n",
```suggestion
    "loader = TextLoader(\"../../modules/state_of_the_union.txt\")\n",
```

2023-11-10 08:37 UTC, sainivedh commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "print(langchain.__file__)"
```suggestion
    ""
```

2023-11-10 08:37 UTC, sainivedh commented on docs/docs/integrations/llms/clarifai.ipynb
> +    "You can use the model_url (for ex: \"https://clarifai.com/anthropic/completion/models/claude-v2\") for intialization."
Could we change the url to GPT3.5/4 models as we are explaining rest of the notebook w.r.t that

2023-11-10 08:37 UTC, sainivedh commented on libs/langchain/langchain/llms/clarifai.py
> +                                                          inference_params=inference_params)
```suggestion
                (inference_params := {}) if inference_params is None else inference_params
                predict_response = model_obj.predict_by_bytes(bytes(prompt, 'utf-8'),
                                                          input_type='text', inference_params=inference_params)
```

2023-11-10 08:37 UTC, sainivedh commented on libs/langchain/langchain/llms/clarifai.py
> +                                                         inference_params=inference_params)
```suggestion
                (inference_params := {}) if inference_params is None else inference_params
                    predict_response = model_obj.predict(inputs=input_batch,
                                                         inference_params=inference_params)
```

2023-11-10 12:27 UTC, mogith-pn commented on libs/langchain/langchain/llms/clarifai.py
> +    def validate_environment(c1q , values: Dict) -> Dict:
done.

2023-11-10 12:28 UTC, mogith-pn commented on libs/langchain/langchain/llms/clarifai.py
> +            print(text)
done removed.

2023-11-10 12:29 UTC, mogith-pn commented on libs/langchain/langchain/vectorstores/clarifai.py
> -        pat: Optional[str] = None,
Sorry, My bad. Actually we should remove pat from all since we are not using it inside any function and we instructing users to intialize pat as env variable. Hence i removed it from all.

2023-11-10 12:29 UTC, mogith-pn commented on libs/langchain/langchain/vectorstores/clarifai.py
> +                continue
Modified to ingest inputs as batch with metadata protos.

2023-11-10 12:30 UTC, mogith-pn commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "loader = TextLoader(\"/Users/mogithpn/Downloads/history2.txt\")\n",
modified.

2023-11-10 12:30 UTC, mogith-pn commented on docs/docs/integrations/vectorstores/clarifai.ipynb
> +    "print(langchain.__file__)"
removed.

2023-11-10 13:14 UTC, sainivedh reviewed
Looks Good to me. Added two last comments

2023-11-10 13:14 UTC, sainivedh commented on libs/langchain/langchain/llms/clarifai.py
> +            clarifai_llm = Clarifai(pat=CLARIFAI_PAT,user_id=USER_ID, app_id=APP_ID, model_id=MODEL_ID)
```suggestion
            clarifai_llm = Clarifai(user_id=USER_ID, app_id=APP_ID, model_id=MODEL_ID)
```
I guess now don't allow pat as arg, so we can remove this?

2023-11-10 13:14 UTC, sainivedh commented on libs/langchain/langchain/llms/clarifai.py
> +                                                          inference_params=inference_params)
Could we please change this too,  
this should've been added to SDK but for now we can add here, writing if else for predict doesn't look good.
`(inference_params := {}) if inference_params is None else inference_params`

2023-11-10 13:34 UTC, mogith-pn commented
@sainivedh modified the function.

2023-11-10 13:36 UTC, sainivedh approved these changes
lgtm!

2023-11-14 13:49 UTC, mogith-pn commented
@sainivedh  updated clarifai versions.

2023-11-15 07:21 UTC, merged